use_frameworks!

target 'SLStart_Example' do
  pod 'SLStart', :path => '../'

  target 'SLStart_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
